### ISSUE TITLE
Running example yields exception

### ISSUE THREAD

**Issue by bdynamic** [Wibias/hass-variables#1]
Running the following example (a bit adapted) on HA 0.118.2 

```
variable:
  test_timer:
    value: 0
    attributes:
      icon: mdi:alarm

automation:
  - alias: Test_auto
    description: ''
    trigger:
      - device_id: 94d39c5b36b862bf2d0995f1d6a3ce04
        domain: deconz
        platform: device
        type: remote_button_short_press
        subtype: turn_on
    action:
      - service: variable.set_variable
        data:
          variable: test_timer
          value: '{{ [((variable.state | int) - 1), 0] | max }}'
```

yields the following error

```
jinja2.exceptions.UndefinedError: 'variable' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 144, in async_prepare_call_from_config
    service_data.update(template.render_complex(config[conf], variables))
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 91, in render_complex
    return {
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 92, in <dictcomp>
    render_complex(key, variables): render_complex(item, variables)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 96, in render_complex
    return value.async_render(variables)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 353, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'variable' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 433, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 432, in _async_call_service_step
    domain, service, service_data = async_prepare_call_from_config(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 146, in async_prepare_call_from_config
    raise HomeAssistantError(f"Error rendering data template: {ex}") from ex
homeassistant.exceptions.HomeAssistantError: Error rendering data template: UndefinedError: 'variable' is undefined

```

**Comment by Wibias** [comment]
Whoops didn't get a notification on this, sorry. Or maybe overseen it. So this is pretty much the same as https://github.com/rogro82/hass-variables/issues/44 but your exact variable and aciton part doesn't throw an error for me. Did you update the files with mine instead of the old not really working files from rogro?
